name: medidata
description: MediData Flutter app
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.0.0
  dio: ^5.0.0
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  open_file: ^3.2.1
  webview_flutter: ^4.0.0
  flutter_pdfview: ^1.2.3
